development:
  adapter: postgresql
  host: localhost
  username: lars
  password: password
  database: localdb

test:
  adapter: postgresql
  host: localhost
  username: lars
  password: password
  database: localdb

