development:
  adapter: postgresql
  host: localhost
  username: lars
  password: password
  database: sample_app_dev

test:
  adapter: postgresql
  host: localhost
  username: lars
  password: password
  database: sample_app_test

